# Exported from Render on 2024-06-03T12:42:20Z
services:
- type: web
  name: mybooks-api
  runtime: docker
  repo: https://github.com/vinniciusgomes/mybooks-api
  plan: free
  envVars:
  - key: GIN_MODE
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  region: virginia
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
